### PR TITLE
Proper messages for unchecking and unstarring items

### LINKED ISSUE #27: check uncheck tasks
**Describe the bug**
when you check an item that has already been checked the program returns item checked even though it actually becomes unchecked

**To Reproduce**
$ tb -t foo
$tb -c 1
$tb -c 1

**Expected behavior**
If I realized that what I had done wasn't actually done I would want to uncheck it so the program should return "# unchecked" if I run --check twice on an item

**Screenshots**

**Technical Info (please complete the following information)**
 - OS: macOS (10.13.6)
 - Node.js Version: v8.11.3
 - Taskbook Version: 0.1.1

**Additional context**

### PR DESCRIPTION
**Pull request by ashinzekene**
Fixes #27 

Shows the right message when unchecking and unstarring items. For example
```
✔  Unchecked tasks: 3, 1
```

### CODE REVIEW

File: lib/render.js [hunk 1]
```diff
@@ -218,12 +218,24 @@ class Render {
     success({prefix, message, suffix});
   }
 
+  markIncomplete(ids) {
+    const [prefix, suffix] = ['\n', grey(ids.join(', '))];
```
[the remark this answers is not in the document]
Comment (rjoydip) [reply lib/render.js]: I think this condition check is not necessary.

[the remark this answers is not in the document]
Comment (novddd) [reply lib/render.js]: The if statement is necessary, @ashinzekene should add them

File: lib/taskbook.js [hunk 2]
```diff
@@ -307,13 +307,25 @@ class Taskbook {
...
+    const checked = [];
+    const unChecked = [];
 
     ids.forEach(id => {
+      if (_data[id].isComplete) {
+        checked.push(id);
+      } else {
+        unChecked.push(id);
+      }
       _data[id].isComplete = !_data[id].isComplete;
```
[the remark this answers is not in the document]
Comment (novddd) [reply lib/taskbook.js]: This part has not been updated yet, i can help out if needed

File: lib/taskbook.js [hunk 3]
```diff
@@ -462,13 +474,25 @@ class Taskbook {
...
+    const unStarred = [];
 
     ids.forEach(id => {
+      if (_data[id].isStarred) {
+        starred.push(id);
+      } else {
+        unStarred.push(id);
+      }
       _data[id].isStarred = !_data[id].isStarred;
     });
```
[the remark this answers is not in the document]
Comment (novddd) [reply lib/taskbook.js]: This part still hasnt been updated, please let me know if you need help, happy to contribute

**Comment by ashinzekene** [comment]
Sorry I have not replied in a while. I'm working on my undergraduate project and I'm far behind schedule.

File: lib/render.js [hunk 4]
```diff
@@ -213,17 +213,41 @@ class Render {
   }
 
   markComplete(ids) {
+    if (ids.length === 0) {
+      return;
+    }
```
Comment (klauscfhq) [inline lib/render.js]: 👌

File: lib/render.js [hunk 5]
```diff
@@ -213,17 +213,41 @@ class Render {
...
   }
 
+  markIncomplete(ids) {
+    if (ids.length === 0) {
+      return;
+    }
+    const [prefix, suffix] = ['\n', grey(ids.join(', '))];
+    const message = `Unchecked ${ids.length > 1 ? 'tasks' : 'task'}:`;
+    success({prefix, message, suffix});
+  }
```
Comment (klauscfhq) [inline lib/render.js]: 👌

File: lib/render.js [hunk 6]
```diff
@@ -213,17 +213,41 @@ class Render {
...
+
   markStarred(ids) {
+    if (ids.length === 0) {
+      return;
+    }
```
Comment (klauscfhq) [inline lib/render.js]: 👌

File: lib/render.js [hunk 7]
```diff
@@ -213,17 +213,41 @@ class Render {
...
   }
 
+  markUnstarred(ids) {
+    if (ids.length === 0) {
+      return;
+    }
+    const [prefix, suffix] = ['\n', grey(ids.join(', '))];
+    const message = `Unstarred ${ids.length > 1 ? 'items' : 'item'}:`;
+    success({prefix, message, suffix});
+  }
```
Comment (klauscfhq) [inline lib/render.js]: 👌

File: lib/taskbook.js [hunk 8]
```diff
@@ -307,13 +307,16 @@ class Taskbook {
   checkTasks(ids) {
     ids = this._validateIDs(ids);
     const {_data} = this;
+    const [checked, unChecked] = [[], []];
```
Comment (klauscfhq) [inline lib/taskbook.js]: It is completely Ok to avoid the camel-case here and go for `unchecked` as a variable name:

```js
const [checked, unchecked] = [[], []];
```

File: lib/taskbook.js [hunk 9]
```diff
@@ -307,13 +307,16 @@ class Taskbook {
...
 
     ids.forEach(id => {
       _data[id].isComplete = !_data[id].isComplete;
+      return _data[id].isComplete ? unChecked.push(id) : checked.push(id);
```
Comment (klauscfhq) [inline lib/taskbook.js]: Items whose `isComplete` attribute is updated to `true` should be placed in the `checked` array and items whose 
`isComplete` attribute is updated to `false` should be placed in the `unchecked` one:

```js
return _data[id].isComplete ? checked.push(id) : unchecked.push(id);
```

File: lib/taskbook.js [hunk 10]
```diff
@@ -307,13 +307,16 @@ class Taskbook {
...
     });
 
     this._save(_data);
-    render.markComplete(ids);
+    render.markIncomplete(checked);
+    render.markComplete(unChecked);
```
Comment (klauscfhq) [inline lib/taskbook.js]: Checked items should be displayed before the unchecked ones, just like with the display of the starred/unstarred items on line 476:

```js
 render.markComplete(checked);
 render.markIncomplete(unchecked);
```

File: lib/taskbook.js [hunk 11]
```diff
@@ -462,13 +465,16 @@ class Taskbook {
   starItems(ids) {
     ids = this._validateIDs(ids);
     const {_data} = this;
+    const [starred, unStarred] = [[], []];
```
Comment (klauscfhq) [inline lib/taskbook.js]: The camel-case can be dropped here as well:

```js
const [starred, unstarred] = [[], []];
```

File: lib/taskbook.js [hunk 12]
```diff
@@ -462,13 +465,16 @@ class Taskbook {
...
 
     ids.forEach(id => {
       _data[id].isStarred = !_data[id].isStarred;
+      return _data[id].isStarred ? unStarred.push(id) : starred.push(id);
     });
 
     this._save(_data);
-    render.markStarred(ids);
+    render.markStarred(unStarred);
+    render.markUnstarred(starred);
```
Comment (klauscfhq) [inline lib/taskbook.js]:
```js
render.markStarred(starred);
render.markUnstarred(unstarred);
```

File: lib/taskbook.js (hunk 9 above)
Comment (ashinzekene) [reply lib/taskbook.js]: No. I think it is right this way. The line above has already changed the status of the tasks

Comment (ashinzekene) [reply lib/taskbook.js]: `render.markIncomplete(checked);`
and then this

Comment (klauscfhq) [reply lib/taskbook.js]: The process you are describing is indeed identical, but these arrays, `checked[]` & `unchecked[]`, are meant to store item IDs based on each item's updated `isComplete` attribute value, and not on the original/database-stored one, thus reversing them will lead to a clearer and more obvious behavior for future readers. For example: an item stored in the database with its `isComplete` attribute set to `false` (unchecked), once selected & checked by the user, will have its value updated to its opposite `true` (checked), thus its ID should be passed to the `checked` array. The same holds for the opposite case, where the item is initial marked as complete.

**Comment by ashinzekene** [comment]
I think we are good now
